### PR TITLE
Correct Istanbul and Yuzhno-Sakhalinsk timezones

### PR DESCRIPTION
**Pull request by leodrivera**
https://github.com/home-assistant/core/issues/81661

### CODE REVIEW

**Comment by anonim-no** [comment]
`"Asia/Vladivostok": "(GMT+11:00) Moscow+07 - Yuzhno-Sakhalinsk",`
It is not right
Need to revert:
`"Asia/Vladivostok": "(GMT+10:00) Moscow+07 - Vladivostok",`
And add new:
`"Asia/Yuzhno-Sakhalinsk": "(GMT+11:00) Moscow+08 - Yuzhno-Sakhalinsk",`

Yuzhno-Sakhalinsk was previously in the same time zone with Vladivostok. Now they are in different time zones

Vladivostok - https://en.wikipedia.org/wiki/Vladivostok
Yuzhno-Sakhalinsk - https://en.wikipedia.org/wiki/Yuzhno-Sakhalinsk

**Comment by leodrivera** [comment]
I've just made the suggested corrections.

**Comment by anonim-no** [comment]
> I've just made the suggested corrections.

That's right.  Thank you!

**Comment by sanohin** [comment]
Released in [v1.2.0](https://github.com/sanohin/google-timezones-json/releases/tag/v1.2.0)

**Pull request merged**
